"""发布清单补上 Agent 版本:**为空 = 那次发布没绑 Agent**

## 补的是一个洞,不是一个需求

`release_manifests` 自称「完整依赖清单,全部是确切版本」,
记了 prompt / 连接 / 索引 / 检索配置 / 模型产物 ——
**唯独没有 Agent 版本**。而 Agent 版本里装着 `tools`(它能用哪些工具)。

发现它的场景很具体:做工具详情的「引用与运行」那一页时,
要回答「**停用这个工具会不会影响线上**」——
而**整个库答不出来**(实查:全库带 agent 字样的列只有
`agent_versions.agent_id` 和 `graph_drafts.agent_id`)。

> 一张自称「完整依赖清单」的表,**少一样就答不全它自己承诺的问题**。

## ⚠️ 这一列为空 = 那次发布没绑 Agent,**不是「数据坏了」**

清单是**不可变**的 —— 已有的清单这一列永远是 NULL,不可能回去补。
读成「数据坏了」然后报错的话,**所有历史发布记录会一起失效**,
而建表、迁移、`alembic check` 全是绿的。

今天第二次做这个决定:`agent_versions.tool_loading_type` 那一列定的是
「空 = 全部加载」—— 同一个形状,同一个理由。

## ⚠️ 「有一份清单记着它」不等于「生产正指着那一份」

生产在跑哪一版的**真相源是 `environment_bindings`(环境指针)**,
而一份三个月前回滚掉的清单照样记着那个 Agent 版本。
所以查「在不在生产上」要走:
**环境指针 → 发布清单 → Agent 版本 → tools**,而不是只查清单。

## 确认过

`upgrade()` 只有 1 个 add_column(**可空**)+ 1 个 create_foreign_key
(带 `ondelete=RESTRICT` 和 `project_id`,项目隔离),**零个 drop / alter**。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14979be496d5'
down_revision: Union[str, Sequence[str], None] = '5aa79487bf0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release_manifests', sa.Column('agent_version_id', sa.Text(), nullable=True))
    op.create_foreign_key('fk_release_manifests_agent_versions', 'release_manifests', 'agent_versions', ['project_id', 'agent_version_id'], ['project_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_release_manifests_agent_versions', 'release_manifests', type_='foreignkey')
    op.drop_column('release_manifests', 'agent_version_id')
    # ### end Alembic commands ###
