"""检索试跑记录表(业务 10-08 要的栏目)+ CHECK 约束机制

Revision ID: 35fcfbfaf961
Revises: d2ba00576e59
Create Date: 2026-10-08 13:50:39.566320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35fcfbfaf961'
down_revision: Union[str, Sequence[str], None] = 'd2ba00576e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrieval_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('index_build_id', sa.Text(), nullable=False),
    sa.Column('knowledge_base_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('rewritten_query', sa.Text(), nullable=True),
    sa.Column('chain_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recall_count', sa.Integer(), nullable=True),
    sa.Column('selected_count', sa.Integer(), nullable=True),
    sa.Column('context_token_count', sa.Integer(), nullable=True),
    sa.Column('answer_status', sa.Text(), nullable=True),
    sa.Column('answer_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rating_reason', sa.Text(), nullable=True),
    sa.Column('rated_by', sa.Text(), nullable=True),
    sa.Column('rated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.CheckConstraint("answer_status in ('答了', '证据不够', '这次没要', '跑不成')", name='ck_retrieval_runs_answer_status'),
    sa.CheckConstraint("source in ('检索实验室', 'chat')", name='ck_retrieval_runs_source'),
    sa.CheckConstraint('rating is null or (rating between 1 and 5)', name='ck_retrieval_runs_rating_1_5'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_retrieval_runs_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'index_build_id'], ['index_builds.project_id', 'index_builds.id'], name='fk_retrieval_runs_index_builds', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'knowledge_base_id'], ['knowledge_bases.project_id', 'knowledge_bases.id'], name='fk_retrieval_runs_knowledge_bases', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_retrieval_runs')
    )
    op.create_index('ix_retrieval_runs_proj_updated', 'retrieval_runs', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_retrieval_runs_proj_updated', table_name='retrieval_runs')
    op.drop_table('retrieval_runs')
    # ### end Alembic commands ###
