"""jobs 加 config_snapshot:排队中的任务要跑提交时那份配置,不是执行时现查的草稿

Revision ID: 3b8347866845
Revises: 71039b5b6737
Create Date: 2026-10-03 21:54:13.515813


## 为什么要这一列

外部审阅(2026-10-03,`产品经理面试/output/lanxiu-review-20261003/`)第 4.5 条:
**Prompt 调试任务只存提交哈希,Worker 仍读可变草稿。**
已在当前 HEAD 上重新核过,**问题仍存在**。

原来的链是:

    POST /prompt-runs  → jobs 存 snapshot_hash(messages/变量/参数/输入 的哈希)
    worker 捞到       → 按 prompt_id **重查 prompt_drafts** → 用现在的草稿跑

于是「提交 A → 排队 → 有人把草稿改成 B → Worker 跑的是 B」,
而那次运行在界面上看起来就是 A 的结果。

⚠️ 最刺眼的是提交那一侧的注释,它写着:

> 快照哈希:提交时那份配置 —— **任务建好之后改 Prompt 不影响它。**

那句话是假的。**一句声称自己已经做到的注释,比没有注释更糟** ——
它让读代码的人不去核。

## 为什么是存内容,而不是「Worker 多比一次哈希」

审阅把「比哈希就失败」列为**过渡方案**,理由对:
**存一个哈希还原不了内容** —— 它只能让那次运行失败,不能让它跑原来那一版。
而调试运行排队几秒到几分钟,期间改草稿是**正常操作**(人就是在调它)。
所以存内容:`config_snapshot` 固化 messages / 变量定义 / 参数 / 输入,
`snapshot_hash` 降级成它的校验和(执行前比一次)。

## 为什么可空

库里已有的 jobs 行没有这一列。给默认值 `'{}'` 的话,
「这是改之前建的老任务」和「这次提交没存快照」在数据上长得一样 ——
而后者是个 bug。所以:**NULL = 老任务**,Worker 遇到它**明确失败**
(`SNAPSHOT_MISSING`),不退回现查草稿。

## 为什么挂 `jobs` 而不是新建一张表

`_snapshot` 这个后缀在 `fieldtypes.py` 里早就登记了,说明写的正是这件事:
「快照:建任务时固化,之后改配置不影响它」。`execution_runs.input_snapshot`
就是同一个形状。新建一张表会多一个要和 jobs 生命周期对齐的东西,
而它们本来就是一对一。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b8347866845'
down_revision: Union[str, Sequence[str], None] = '71039b5b6737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'config_snapshot')
    # ### end Alembic commands ###
