"""初始表结构:从契约登记表派生

Revision ID: 51331b3d286a
Revises: 
Create Date: 2026-09-26 09:39:49.428452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51331b3d286a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_organizations')
    )
    op.create_table('pricing_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model_id', sa.Text(), nullable=True),
    sa.Column('unit_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('effective_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_pricing_versions')
    )
    op.create_index('ix_pricing_versions_hash', 'pricing_versions', ['content_hash'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('retention_policy', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('allowed_providers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_egress_policy', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_projects'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_projects_org_id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('pipeline_type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_applications_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_applications')
    )
    op.create_index('ix_applications_proj_updated', 'applications', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('target_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('environment', sa.Text(), nullable=True),
    sa.Column('at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('redacted_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_audit_events_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_audit_events')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('period', sa.Text(), nullable=True),
    sa.Column('limit_amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('reserved_amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_budgets_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_budgets')
    )
    op.create_index('ix_budgets_proj_updated', 'budgets', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('connection_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('connection_id', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('secret_ref', sa.Text(), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_connection_versions_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_connection_versions')
    )
    op.create_index('ix_connection_versions_proj_updated', 'connection_versions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_datasets_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_datasets')
    )
    op.create_index('ix_datasets_proj_updated', 'datasets', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('candidate_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('baseline_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dataset_version_id', sa.Text(), nullable=True),
    sa.Column('scorer_version', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_evaluations_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_evaluations')
    )
    op.create_index('ix_evaluations_proj_status', 'evaluations', ['project_id', 'status'], unique=False)
    op.create_index('ix_evaluations_proj_updated', 'evaluations', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('target_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('lease_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_jobs_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_jobs'),
    sa.UniqueConstraint('idempotency_key', name='uq_jobs_idempotency_key')
    )
    op.create_index('ix_jobs_proj_status', 'jobs', ['project_id', 'status'], unique=False)
    op.create_index('ix_jobs_proj_updated', 'jobs', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('acl', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('embedding_purpose_connection_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_knowledge_bases_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_knowledge_bases')
    )
    op.create_index('ix_knowledge_bases_proj_status', 'knowledge_bases', ['project_id', 'status'], unique=False)
    op.create_index('ix_knowledge_bases_proj_updated', 'knowledge_bases', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('project_id', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('special_grants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_memberships_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pk_memberships'),
    sa.UniqueConstraint('organization_id', 'project_id', 'user_id', name='uq_memberships_org_proj_user')
    )
    op.create_index('ix_memberships_proj_status', 'memberships', ['project_id', 'status'], unique=False)
    op.create_index('ix_memberships_proj_updated', 'memberships', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('model_connections',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('adapter', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_model_connections_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_model_connections')
    )
    op.create_index('ix_model_connections_proj_status', 'model_connections', ['project_id', 'status'], unique=False)
    op.create_index('ix_model_connections_proj_updated', 'model_connections', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('prompt_drafts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variable_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_prompt_drafts_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_prompt_drafts')
    )
    op.create_index('ix_prompt_drafts_proj_updated', 'prompt_drafts', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variable_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_prompt_versions_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_prompt_versions'),
    sa.UniqueConstraint('key', 'content_hash', name='uq_prompt_versions_key_content_hash')
    )
    op.create_index('ix_prompt_versions_hash', 'prompt_versions', ['content_hash'], unique=False)
    op.create_index('ix_prompt_versions_proj_updated', 'prompt_versions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('retrieval_config_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('recall_modes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidate_k', sa.Integer(), nullable=True),
    sa.Column('fusion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rerank', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_budget_tokens', sa.Integer(), nullable=True),
    sa.Column('final_chunk_limit', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_retrieval_config_versions_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_retrieval_config_versions')
    )
    op.create_index('ix_retrieval_config_versions_hash', 'retrieval_config_versions', ['content_hash'], unique=False)
    op.create_index('ix_retrieval_config_versions_proj_updated', 'retrieval_config_versions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('usage_ledger',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('event_key', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('pricing_version_id', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('amount_known', sa.Boolean(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_usage_ledger_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_usage_ledger'),
    sa.UniqueConstraint('event_key', name='uq_usage_ledger_event_key')
    )
    op.create_table('dataset_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('dataset_id', sa.Text(), nullable=True),
    sa.Column('split_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_dataset_versions_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'dataset_id'], ['datasets.project_id', 'datasets.id'], name='fk_dataset_versions_datasets', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_dataset_versions'),
    sa.UniqueConstraint('dataset_id', 'content_hash', name='uq_dataset_versions_dataset_id_content_hash')
    )
    op.create_index('ix_dataset_versions_hash', 'dataset_versions', ['content_hash'], unique=False)
    op.create_index('ix_dataset_versions_proj_updated', 'dataset_versions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('knowledge_base_id', sa.Text(), nullable=True),
    sa.Column('source_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acl_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disabled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_documents_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'knowledge_base_id'], ['knowledge_bases.project_id', 'knowledge_bases.id'], name='fk_documents_knowledge_bases', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_documents')
    )
    op.create_index('ix_documents_proj_updated', 'documents', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('evaluation_items',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('evaluation_id', sa.Text(), nullable=True),
    sa.Column('sample_id', sa.Text(), nullable=True),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_evaluation_items_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'evaluation_id'], ['evaluations.project_id', 'evaluations.id'], name='fk_evaluation_items_evaluations', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_evaluation_items')
    )
    op.create_index('ix_evaluation_items_proj_updated', 'evaluation_items', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('index_builds',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('knowledge_base_id', sa.Text(), nullable=True),
    sa.Column('retrieval_config_version_id', sa.Text(), nullable=True),
    sa.Column('embedding_model_id', sa.Text(), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_index_builds_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'knowledge_base_id'], ['knowledge_bases.project_id', 'knowledge_bases.id'], name='fk_index_builds_knowledge_bases', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'retrieval_config_version_id'], ['retrieval_config_versions.project_id', 'retrieval_config_versions.id'], name='fk_index_builds_retrieval_config_versions', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_index_builds')
    )
    op.create_index('ix_index_builds_proj_status', 'index_builds', ['project_id', 'status'], unique=False)
    op.create_index('ix_index_builds_proj_updated', 'index_builds', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.Column('seq', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_job_events_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'job_id'], ['jobs.project_id', 'jobs.id'], name='fk_job_events_jobs', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_job_events'),
    sa.UniqueConstraint('job_id', 'seq', name='uq_job_events_job_id_seq')
    )
    op.create_table('outbox',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_outbox_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'job_id'], ['jobs.project_id', 'jobs.id'], name='fk_outbox_jobs', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_outbox')
    )
    op.create_index('ix_outbox_proj_updated', 'outbox', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('release_manifests',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('application_id', sa.Text(), nullable=True),
    sa.Column('prompt_version_id', sa.Text(), nullable=True),
    sa.Column('connection_version_id', sa.Text(), nullable=True),
    sa.Column('index_build_id', sa.Text(), nullable=True),
    sa.Column('retrieval_config_version_id', sa.Text(), nullable=True),
    sa.Column('model_artifact_id', sa.Text(), nullable=True),
    sa.Column('evaluation_id', sa.Text(), nullable=True),
    sa.Column('approval', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_release_manifests_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'application_id'], ['applications.project_id', 'applications.id'], name='fk_release_manifests_applications', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'prompt_version_id'], ['prompt_versions.project_id', 'prompt_versions.id'], name='fk_release_manifests_prompt_versions', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_release_manifests'),
    sa.UniqueConstraint('application_id', 'content_hash', name='uq_release_manifests_application_id_content_hash')
    )
    op.create_index('ix_release_manifests_hash', 'release_manifests', ['content_hash'], unique=False)
    op.create_index('ix_release_manifests_proj_updated', 'release_manifests', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('samples',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('dataset_id', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Text(), nullable=True),
    sa.Column('split', sa.Text(), nullable=True),
    sa.Column('group_id', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_samples_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'dataset_id'], ['datasets.project_id', 'datasets.id'], name='fk_samples_datasets', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_samples')
    )
    op.create_index('ix_samples_hash', 'samples', ['content_hash'], unique=False)
    op.create_index('ix_samples_proj_updated', 'samples', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('document_id', sa.Text(), nullable=True),
    sa.Column('object_key', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('effective_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_document_versions_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'document_id'], ['documents.project_id', 'documents.id'], name='fk_document_versions_documents', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_document_versions'),
    sa.UniqueConstraint('document_id', 'content_hash', name='uq_document_versions_document_id_content_hash')
    )
    op.create_index('ix_document_versions_hash', 'document_versions', ['content_hash'], unique=False)
    op.create_index('ix_document_versions_proj_updated', 'document_versions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('environment_bindings',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('application_id', sa.Text(), nullable=True),
    sa.Column('environment', sa.Text(), nullable=True),
    sa.Column('release_manifest_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_environment_bindings_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'release_manifest_id'], ['release_manifests.project_id', 'release_manifests.id'], name='fk_environment_bindings_release_manifests', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_environment_bindings')
    )
    op.create_index('ix_environment_bindings_proj_updated', 'environment_bindings', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('evaluation_item_id', sa.Text(), nullable=True),
    sa.Column('dimension', sa.Text(), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('value_known', sa.Boolean(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('scorer_version', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('by', sa.Text(), nullable=True),
    sa.Column('at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('supersedes_score_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_scores_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'evaluation_item_id'], ['evaluation_items.project_id', 'evaluation_items.id'], name='fk_scores_evaluation_items', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_scores')
    )
    op.create_index('ix_scores_proj_updated', 'scores', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('traces',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('application_id', sa.Text(), nullable=True),
    sa.Column('release_manifest_id', sa.Text(), nullable=True),
    sa.Column('environment', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_traces_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'application_id'], ['applications.project_id', 'applications.id'], name='fk_traces_applications', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'release_manifest_id'], ['release_manifests.project_id', 'release_manifests.id'], name='fk_traces_release_manifests', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_traces')
    )
    op.create_index('ix_traces_started_app', 'traces', [sa.literal_column('started_at DESC'), 'application_id'], unique=False)
    op.create_table('training_jobs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dataset_version_id', sa.Text(), nullable=True),
    sa.Column('base_model', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('param_update_method', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('image_digest', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_training_jobs_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'dataset_version_id'], ['dataset_versions.project_id', 'dataset_versions.id'], name='fk_training_jobs_dataset_versions', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_training_jobs'),
    sa.UniqueConstraint('external_id', name='uq_training_jobs_external_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_training_jobs_idempotency_key')
    )
    op.create_index('ix_training_jobs_proj_status', 'training_jobs', ['project_id', 'status'], unique=False)
    op.create_index('ix_training_jobs_proj_updated', 'training_jobs', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('training_job_id', sa.Text(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('object_key', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_checkpoints_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'training_job_id'], ['training_jobs.project_id', 'training_jobs.id'], name='fk_checkpoints_training_jobs', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_checkpoints')
    )
    op.create_index('ix_checkpoints_proj_updated', 'checkpoints', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('document_version_id', sa.Text(), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_hash', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_chunks_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'document_version_id'], ['document_versions.project_id', 'document_versions.id'], name='fk_chunks_document_versions', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_chunks')
    )
    op.create_index('ix_chunks_proj_updated', 'chunks', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('promoted_sample_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_feedback_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'trace_id'], ['traces.project_id', 'traces.id'], name='fk_feedback_traces', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_feedback')
    )
    op.create_index('ix_feedback_proj_updated', 'feedback', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('model_artifacts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('training_job_id', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('base_model', sa.Text(), nullable=True),
    sa.Column('tokenizer_ref', sa.Text(), nullable=True),
    sa.Column('file_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('usable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_model_artifacts_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'training_job_id'], ['training_jobs.project_id', 'training_jobs.id'], name='fk_model_artifacts_training_jobs', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_model_artifacts')
    )
    op.create_index('ix_model_artifacts_hash', 'model_artifacts', ['content_hash'], unique=False)
    op.create_index('ix_model_artifacts_proj_updated', 'model_artifacts', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('spans',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('parent_span_id', sa.Text(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('input_ref', sa.Text(), nullable=True),
    sa.Column('output_ref', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_spans_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'trace_id'], ['traces.project_id', 'traces.id'], name='fk_spans_traces', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_spans')
    )
    op.create_table('index_members',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('index_build_id', sa.Text(), nullable=True),
    sa.Column('chunk_id', sa.Text(), nullable=True),
    sa.Column('embedding_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_index_members_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'chunk_id'], ['chunks.project_id', 'chunks.id'], name='fk_index_members_chunks', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'index_build_id'], ['index_builds.project_id', 'index_builds.id'], name='fk_index_members_index_builds', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_index_members')
    )
    op.create_index('ix_index_members_proj_updated', 'index_members', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_index_members_proj_updated', table_name='index_members')
    op.drop_table('index_members')
    op.drop_table('spans')
    op.drop_index('ix_model_artifacts_proj_updated', table_name='model_artifacts')
    op.drop_index('ix_model_artifacts_hash', table_name='model_artifacts')
    op.drop_table('model_artifacts')
    op.drop_index('ix_feedback_proj_updated', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_chunks_proj_updated', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_checkpoints_proj_updated', table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index('ix_training_jobs_proj_updated', table_name='training_jobs')
    op.drop_index('ix_training_jobs_proj_status', table_name='training_jobs')
    op.drop_table('training_jobs')
    op.drop_index('ix_traces_started_app', table_name='traces')
    op.drop_table('traces')
    op.drop_index('ix_scores_proj_updated', table_name='scores')
    op.drop_table('scores')
    op.drop_index('ix_environment_bindings_proj_updated', table_name='environment_bindings')
    op.drop_table('environment_bindings')
    op.drop_index('ix_document_versions_proj_updated', table_name='document_versions')
    op.drop_index('ix_document_versions_hash', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('ix_samples_proj_updated', table_name='samples')
    op.drop_index('ix_samples_hash', table_name='samples')
    op.drop_table('samples')
    op.drop_index('ix_release_manifests_proj_updated', table_name='release_manifests')
    op.drop_index('ix_release_manifests_hash', table_name='release_manifests')
    op.drop_table('release_manifests')
    op.drop_index('ix_outbox_proj_updated', table_name='outbox')
    op.drop_table('outbox')
    op.drop_table('job_events')
    op.drop_index('ix_index_builds_proj_updated', table_name='index_builds')
    op.drop_index('ix_index_builds_proj_status', table_name='index_builds')
    op.drop_table('index_builds')
    op.drop_index('ix_evaluation_items_proj_updated', table_name='evaluation_items')
    op.drop_table('evaluation_items')
    op.drop_index('ix_documents_proj_updated', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_dataset_versions_proj_updated', table_name='dataset_versions')
    op.drop_index('ix_dataset_versions_hash', table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_table('usage_ledger')
    op.drop_index('ix_retrieval_config_versions_proj_updated', table_name='retrieval_config_versions')
    op.drop_index('ix_retrieval_config_versions_hash', table_name='retrieval_config_versions')
    op.drop_table('retrieval_config_versions')
    op.drop_index('ix_prompt_versions_proj_updated', table_name='prompt_versions')
    op.drop_index('ix_prompt_versions_hash', table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index('ix_prompt_drafts_proj_updated', table_name='prompt_drafts')
    op.drop_table('prompt_drafts')
    op.drop_index('ix_model_connections_proj_updated', table_name='model_connections')
    op.drop_index('ix_model_connections_proj_status', table_name='model_connections')
    op.drop_table('model_connections')
    op.drop_index('ix_memberships_proj_updated', table_name='memberships')
    op.drop_index('ix_memberships_proj_status', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_knowledge_bases_proj_updated', table_name='knowledge_bases')
    op.drop_index('ix_knowledge_bases_proj_status', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index('ix_jobs_proj_updated', table_name='jobs')
    op.drop_index('ix_jobs_proj_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_evaluations_proj_updated', table_name='evaluations')
    op.drop_index('ix_evaluations_proj_status', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('ix_datasets_proj_updated', table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('ix_connection_versions_proj_updated', table_name='connection_versions')
    op.drop_table('connection_versions')
    op.drop_index('ix_budgets_proj_updated', table_name='budgets')
    op.drop_table('budgets')
    op.drop_table('audit_events')
    op.drop_index('ix_applications_proj_updated', table_name='applications')
    op.drop_table('applications')
    op.drop_table('projects')
    op.drop_index('ix_pricing_versions_hash', table_name='pricing_versions')
    op.drop_table('pricing_versions')
    op.drop_table('organizations')
    # ### end Alembic commands ###
