"""jobs 补齐规格 §19.3 点名的字段(阶段/心跳/已处理数/错误码/快照哈希/重试)

Revision ID: 55de922d112c
Revises: 51331b3d286a
Create Date: 2026-09-26 12:13:47.177996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55de922d112c'
down_revision: Union[str, Sequence[str], None] = '51331b3d286a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('stage', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('max_attempts', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('heartbeat_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('processed_count', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('cancel_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('error_code', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('snapshot_hash', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('next_retry_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('needs_human_check', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'needs_human_check')
    op.drop_column('jobs', 'next_retry_at')
    op.drop_column('jobs', 'snapshot_hash')
    op.drop_column('jobs', 'error_detail')
    op.drop_column('jobs', 'error_code')
    op.drop_column('jobs', 'cancel_at')
    op.drop_column('jobs', 'processed_count')
    op.drop_column('jobs', 'heartbeat_at')
    op.drop_column('jobs', 'max_attempts')
    op.drop_column('jobs', 'stage')
    # ### end Alembic commands ###
