"""加旋钮方案表:后台当澜绣 V3 的控制面

搬家说明(`已搬走.md`)的第二条:「Agent 配置 → `agent/knobs.py` 的 6 个旋钮」。

## ⚠️ 为什么新加一张表,而不是塞进 `agent_versions`

搬家说明批评过的正是「**仓库里有了两套「调 agent」的东西**」。
而后台的 `agent_versions` 是**后台自己的** Agent 模型
(prompt 版本 / 工具 / 预算 / 上下文策略),这 6 个旋钮管的是
**澜绣 V3**(`agentsite/sdk.py`)怎么跑 —— 两件事。

而且塞不干净:「想多深」和「交付前体检」在 `agent_versions` 的字段里
**没有对应物**,硬塞只会让那个对象的语义变脏。

## 为什么只有一张表,没有版本表

一个「方案」本身就是一次实验(`.feynman/prompt_candidates/{号}.json`
记着「改了什么、为什么改、跑出来什么分」)。改一个方案就是改那次实验,
要做新实验就建新方案 —— **再套一层版本表只会多一个没人用的维度。**

## 旋钮的**定义**不在这张表里

「有哪 6 个旋钮、取值、默认值」在 `knobs.py` 的 `旋钮表`,接口现读。
不在后台复制 —— 复制的那份会和代码漂,而漂开时后台上会多出一个
**拖了什么都不会变的滑块**(`knobs.py` 自己的话)。

## 确认过

`upgrade()` 段内**零个 drop / alter** —— 1 张 create_table + 2 个 create_index。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5aa79487bf0e'
down_revision: Union[str, Sequence[str], None] = 'b113f98fb970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knob_plans',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('exported_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('file_hash', sa.Text(), nullable=True),
    sa.Column('draft_revision', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_knob_plans_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_knob_plans')
    )
    op.create_index('ix_knob_plans_proj_status', 'knob_plans', ['project_id', 'status'], unique=False)
    op.create_index('ix_knob_plans_proj_updated', 'knob_plans', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knob_plans_proj_updated', table_name='knob_plans')
    op.drop_index('ix_knob_plans_proj_status', table_name='knob_plans')
    op.drop_table('knob_plans')
    # ### end Alembic commands ###
