"""tool_versions 加 model_aliases/when_to_use/task_examples:§8.2 模型说明页签

Revision ID: 71039b5b6737
Revises: 79394b770948
Create Date: 2026-10-03 20:13:34.754802

## 为什么要这三列

规格 §8.2 的「模型说明」页签要「模型可见名称、描述、**适用/不适用场景、别名、
任务示例**」—— 七个页签里只剩这一个没做。而它不是一个孤立的页签:

10-03 工具筛选那条线收口时量出来(`docs/选型/结论-工具筛选-20261003.md`):

> **用户问的是业务,工具说明写的是系统。**

两个独立留出集在同一处失败 —— **5 道题的「需要的工具」和「问法」一个共同片段都没有**:

    藏青 S 码那件马面裙现在还能发几件?   需要「查现货」    零重叠
    灰缬能做在浅色棉麻上吗?              需要「相容矩阵」  零重叠
    我今天有什么活? / 今天该我核什么?                     零重叠
    PT01 这个版型的裁片用料占比是多少?                     零重叠

这三列正好对着这件事:**别名**管业务话到系统话的映射;**适用/不适用**管
「什么时候该用它」;**任务示例**是真实问法,而它同时是筛选器的检索语料。

## 为什么挂在 `tool_versions` 而不是 `tool_definitions`

`tool_versions` 是**不可变子对象**,所以改一条别名就是出一个新版本。
这正是要的:**别名是模型实际会读到的内容**,改了它等于改了工具说明,
而 §16.3 的既有约定是「说明变了要出新版本」—— 否则引用老版本的 Agent
指着的那份说明已经不是现在这一份了。

## 三列为什么都可空(而不是 NOT NULL DEFAULT '[]')

库里已经有 81 个工具版本,它们全都没有这三样。
给个 `'[]'` 的默认值会让「**这个工具还没人填别名**」和
「**有人看过,确认它不需要别名**」在数据上长得一模一样 ——
而页签的全部意义就是让人把前者变成后者(尤其那 7 个 `kb_*`:
现有的 121 条别名覆盖 47/81 个工具,`kb_*` 那一族一条都没有)。
**NULL 是「没说过」,`[]` 是「说过:没有」。** 这两件事要分得开。

## 这一步之前先查过什么

加 `_aliases` / `_examples` 两个后缀约定之前,查了库里和契约里哪些列会被它们命中:
**库里 0 列、契约 303 个字段里 0 个**。这条规矩来自 `_action` 那次 ——
它差点把 `redaction`(JSONB)改成 TEXT。

`when_to_use` **故意不走后缀**(走 `fieldtypes.显式类型` 点名):
`_use` 是个动词,不是这套契约已经在用的命名习惯,
登记它等于宣布「以后任何以 use 结尾的列都是 JSONB」。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71039b5b6737'
down_revision: Union[str, Sequence[str], None] = '79394b770948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_versions', sa.Column('model_aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tool_versions', sa.Column('when_to_use', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tool_versions', sa.Column('task_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_versions', 'task_examples')
    op.drop_column('tool_versions', 'when_to_use')
    op.drop_column('tool_versions', 'model_aliases')
    # ### end Alembic commands ###
