"""对齐库和契约_09_29手写迁移起错了索引和外键名_并去掉只追加表上的三列

Revision ID: 78e69d312111
Revises: 04960cbd2d9f
Create Date: 2026-10-01 21:32:41.317879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78e69d312111'
down_revision: Union[str, Sequence[str], None] = '04960cbd2d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """让**库**跟上契约 —— 09-29 我手写那四个迁移时起错了名字、
    还给一张「只追加」的表加了 revision/updated_at/archived_at。

    ## ⚠️ 这个迁移是 autogenerate 出来的,但**前面两版都被我扔了**

    第一版它要**删掉两条真约束**:
      · `deployments (project_id, idempotency_key)` 唯一 —— 幂等的全部依靠
      · `application_drafts (project_id, application_id)` 唯一 ——
        「一个应用只有一份候选」这句话的落点

    第二版它要把**四列改成可空**:`deployments.status/environment/
    model_artifact_id`、`application_drafts.application_id`。

    两次的根因都是**契约漏声明**,而
    > **autogenerate 做的是「让库跟上模型」—— 模型漏声明的时候,
    > 它会安静地删掉一条真约束。** 照着跑一遍,库是「对齐」了,
    > 而幂等和「一个应用只有一份候选」这两件事没了,**一句话都不会报**。

    所以先补了声明(`models._额外唯一` 两条、`fieldtypes.按表必填` 四列),
    再生成这一版。**这一版只做三件事,一条约束都没删**:
      ① 补两个按约定该有的索引(proj_updated / proj_status)
      ② 两处外键改成约定的名字,并补上 `ondelete=RESTRICT`
         (原来没有 RESTRICT —— 删父行会级联或者报一个没名字的错)
      ③ 去掉 `deployments` 上的 revision/updated_at/archived_at ——
         那张表声明的是**只追加**,而这三列和那个设计**相矛盾**
         (一次部署是**事件**不是版本)。查过:**没有任何代码读它们**。
    """
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_application_drafts_proj_updated', 'application_drafts', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.drop_constraint(op.f('fk_application_drafts_application'), 'application_drafts', type_='foreignkey')
    op.create_foreign_key('fk_application_drafts_applications', 'application_drafts', 'applications', ['project_id', 'application_id'], ['project_id', 'id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_application_drafts_projects', 'application_drafts', 'projects', ['organization_id', 'project_id'], ['organization_id', 'id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_deployments_project_artifact'), table_name='deployments')
    op.create_index('ix_deployments_proj_status', 'deployments', ['project_id', 'status'], unique=False)
    op.drop_constraint(op.f('fk_deployments_model_artifact'), 'deployments', type_='foreignkey')
    op.create_foreign_key('fk_deployments_model_artifacts', 'deployments', 'model_artifacts', ['project_id', 'model_artifact_id'], ['project_id', 'id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_deployments_projects', 'deployments', 'projects', ['organization_id', 'project_id'], ['organization_id', 'id'], ondelete='RESTRICT')
    op.drop_column('deployments', 'revision')
    op.drop_column('deployments', 'archived_at')
    op.drop_column('deployments', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('deployments', sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('deployments', sa.Column('revision', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_deployments_projects', 'deployments', type_='foreignkey')
    op.drop_constraint('fk_deployments_model_artifacts', 'deployments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_deployments_model_artifact'), 'deployments', 'model_artifacts', ['project_id', 'model_artifact_id'], ['project_id', 'id'])
    op.drop_index('ix_deployments_proj_status', table_name='deployments')
    op.create_index(op.f('ix_deployments_project_artifact'), 'deployments', ['project_id', 'model_artifact_id'], unique=False)
    op.drop_constraint('fk_application_drafts_projects', 'application_drafts', type_='foreignkey')
    op.drop_constraint('fk_application_drafts_applications', 'application_drafts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_application_drafts_application'), 'application_drafts', 'applications', ['project_id', 'application_id'], ['project_id', 'id'])
    op.drop_index('ix_application_drafts_proj_updated', table_name='application_drafts')
    # ### end Alembic commands ###
