"""片段加 `section_titles` —— 路径的无歧义表示是列表,不是拼起来的字符串

## 为什么要这一列

`section_path` 是用 ` / ` 把各级标题**拼起来**的,而全库有
**29 个标题自己的名字里带 ` / `**,比如:

    ## 二、里料 / 衬料常见门幅(生产商规格为主,无标准原文)

拿 ` / ` 拆它,一级会变成两级 —— **而多出来的那一级在数据形状上完全合法**。

实测(2026-10-03):**802 个片段里 44 个(5.5%)的节路径拆不回去**,
其中 **43 个在 `knowledge/`** —— 那正是导进后台的那批语料。

> **路径的无歧义表示是列表,不是用分隔符拼起来的字符串。**

这条是 CI 逼出来的:`test_knowledge_chain` 的判据原来写 `section_path.split(" / ")`,
于是它报「这两个节名原文里没有」——**而那两个名字正是解析器从同一行里拆出来的**。
那条红是对的(路径确实拆不回去),但它的诊断指向了错的方向。

## 为什么是现在补,而不是当时

当时(10-03 上午)只在**内存里**加了 `节标题们`,`parser.py` / `chunker.py` 带着它,
判据也改成读列表 —— 但**没进库**。注释里当时就写明了:
「存进库的那一份仍然是有歧义的 —— 以后要做「按节聚合」或「面包屑」,
得先把它持久化(要改契约 + 迁移)」。

这一版就是那一步。

## `section_path` 一个字不改

它仍然是对外引用和显示用的那一份(`retrieval.py` / `chunker.py` 都在格式化它)。
**要按级别做事的一律读 `section_titles`。** 契约上也写了这句话。

## 旧行怎么办

列**可空**。库里现有 1720 个片段的这一列是 NULL ——
**空 = 那一版切片时还没有这一列**,不是「那个片段没有标题」。
要回填就重跑 `tools/ingest_lanxiu.py`(它按内容哈希幂等,内容没变不会出新版本);
而**不回填也不会错**:读的地方要么用 `section_path`(没变),要么拿不到列表就说拿不到。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79394b770948'
down_revision: Union[str, Sequence[str], None] = 'd41b8170e086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('section_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'section_titles')
    # ### end Alembic commands ###
