"""缓存管理阶段1-2的五个对象:策略草稿/版本、能力快照、运行覆盖、缓存决定

Revision ID: 8b4ab4df1497
Revises: 3b8347866845
Create Date: 2026-10-04 12:26:49.551750


## 为什么只建五张表,不是规格 §15.1 那九张

缓存规格(`产品经理面试/output/cache-management/`,903 行)§4 把交付分成五个阶段:
接入与观测 → 提示词缓存策略 → 精确答案缓存 → 运维与评测 → 语义缓存。
而 §15.1 那九个对象**横跨全部阶段**。

一次全建会建出**四张没人写的表**(答案条目目录、失效代次、清理任务、评测扩展)。
这个仓库的教训:「**摆七个壳子、三个是空的,比摆两个满的糟**」——
空的那几个让人以为「这里没东西」,而真相是「这里还没做」。

**所以这是个决定,不是漏建**,契约里也写明了。
等阶段 3(精确答案缓存)开工时再加那四张;它们的字段后缀**已经登记好**
(`_generation` / `_epoch` / `namespace` …),所以那一步不会再碰 `fieldtypes.py`。

## 这一步之前量了什么

加九个新后缀之前,拿**契约里 306 个字段 + 库里 311 个列名**逐个对过
(这个仓库为「凭名字猜类型」栽过四次):

    _epoch / _generation / _kind / _layer / _options /
    _operations / _config / _completeness        一个都没命中
    _mode                                        命中 3 个已有列
                                                 (execution_mode / load_mode /
                                                  selection_mode)

而那三个在**库里和契约里都是 TEXT** —— 所以登记 `_mode → TEXT` 是确认现状,
**不会改掉任何一列的类型**。

能用已有后缀的没新加:`usage_map`(用 `_map`)、`validation_report`(用 `_report`)、
`storage_ref`(用 `_ref` ——「只存引用,不存内容」正是它的语义)、
`warm_status`(用 `_status`)。少加四个后缀。

## 两个类型选择值得记

**① `supported_operations` 是 JSONB,不是三个布尔。**
供应商 API 支持哪些操作(可列举 / 可删除 / 可关闭)**每一项有三态**:
支持 / 不支持 / **没核查过**。
而一个 NULL 布尔在大多数代码里读起来就是 false ——
于是「没核查过」会变成「不支持」,而这两件事在界面上该显示完全不同的话
(规格 §9:没有列举/删除 API 时不许出现那两个按钮;
 而**没核查过**时该显示「能力待核查」)。

**② `namespace_generation` 用新后缀 `_generation`,不复用 `_revision`。**
`_revision` 在这个仓库是**乐观锁**用的(那条注释自己写着「乐观锁靠它」)。
失效代次和乐观锁版本是两件事 —— 混在一个数里,
「清空了一个范围」会被当成「并发冲突」。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b4ab4df1497'
down_revision: Union[str, Sequence[str], None] = '3b8347866845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_capability_snapshots',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('connection_id', sa.Text(), nullable=True),
    sa.Column('connection_revision', sa.BigInteger(), nullable=True),
    sa.Column('api_kind', sa.Text(), nullable=True),
    sa.Column('cache_mode', sa.Text(), nullable=True),
    sa.Column('ttl_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_prefix_tokens', sa.Integer(), nullable=True),
    sa.Column('supported_operations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_cache_capability_snapshots_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_cache_capability_snapshots')
    )
    op.create_index('ix_cache_capability_snapshots_proj_updated', 'cache_capability_snapshots', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('cache_decisions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('cache_layer', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actual_policy_version', sa.Text(), nullable=True),
    sa.Column('source_trace_id', sa.Text(), nullable=True),
    sa.Column('usage_completeness', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_cache_decisions_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_cache_decisions')
    )
    op.create_index('ix_cache_decisions_proj_updated', 'cache_decisions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('cache_policy_drafts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('policy_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('draft_revision', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_cache_policy_drafts_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_cache_policy_drafts')
    )
    op.create_index('ix_cache_policy_drafts_proj_status', 'cache_policy_drafts', ['project_id', 'status'], unique=False)
    op.create_index('ix_cache_policy_drafts_proj_updated', 'cache_policy_drafts', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('cache_policy_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cache_policy_draft_id', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('policy_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Text(), nullable=True),
    sa.Column('capability_snapshot_ref', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_cache_policy_versions_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_cache_policy_versions')
    )
    op.create_index('ix_cache_policy_versions_hash', 'cache_policy_versions', ['content_hash'], unique=False)
    op.create_index('ix_cache_policy_versions_proj_updated', 'cache_policy_versions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('cache_runtime_overrides',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_cache_runtime_overrides_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_cache_runtime_overrides')
    )
    op.create_index('ix_cache_runtime_overrides_proj_status', 'cache_runtime_overrides', ['project_id', 'status'], unique=False)
    op.create_index('ix_cache_runtime_overrides_proj_updated', 'cache_runtime_overrides', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cache_runtime_overrides_proj_updated', table_name='cache_runtime_overrides')
    op.drop_index('ix_cache_runtime_overrides_proj_status', table_name='cache_runtime_overrides')
    op.drop_table('cache_runtime_overrides')
    op.drop_index('ix_cache_policy_versions_proj_updated', table_name='cache_policy_versions')
    op.drop_index('ix_cache_policy_versions_hash', table_name='cache_policy_versions')
    op.drop_table('cache_policy_versions')
    op.drop_index('ix_cache_policy_drafts_proj_updated', table_name='cache_policy_drafts')
    op.drop_index('ix_cache_policy_drafts_proj_status', table_name='cache_policy_drafts')
    op.drop_table('cache_policy_drafts')
    op.drop_index('ix_cache_decisions_proj_updated', table_name='cache_decisions')
    op.drop_table('cache_decisions')
    op.drop_index('ix_cache_capability_snapshots_proj_updated', table_name='cache_capability_snapshots')
    op.drop_table('cache_capability_snapshots')
    # ### end Alembic commands ###
