"""加工具筛选六张表,并补两个一直没建上的外键

## 这份迁移做两件事

### ① 六张新表(第三份规格 §14.1「工具筛选与按需加载」)

`tool_groups` / `tool_group_versions` / `tool_selection_policies` /
`tool_selection_policy_versions` / `tool_catalog_snapshots` / `selection_decisions`

分界线是**「谁决定它」**:前四张是配置(工具组和策略),
后两张是运行时记录(目录快照和筛选决定)。合成一个对象的话,
「这个 Agent 可以用它」和「这一轮给模型看了它」就分不开了。

### ② 两个**一直没建上**的外键

- `connection_versions.connection_id` → `model_connections`
- `tool_versions.connection_id` → `capability_connections`

两张表的 `entities.py` 里依赖是**声明着的**,而外键从来没建上:
外键是从依赖表名推列名的(`model_connections` → `model_connection_id`),
而实际列名是短名 `connection_id` —— 推不出来,`models.py` 就
**静默 `continue`**。

> 「我声明了依赖所以有外键」和「我声明了依赖但列名推不出来所以没外键」,
> **在登记表上长得一模一样。**

而这个短名是有道理的:`connection_id` 在 `tool_versions` 指
capability_connections、在 `connection_versions` 指 model_connections ——
**同一个列名指向两张不同的父表**,靠列名永远分不开。
所以 `models.py` 里加了 `_依赖列` 显式映射点名这两处,
并新增判据 `tools/fk_dep_check.py`:每一处「声明了依赖却没建成外键」
都要在那里点名 + 写理由。

**补外键之前量过库**(2026-10-02):46 行有效引用、**0 行坏引用** ——
所以这是个安全的收紧。如果当时有坏行,就不能直接加,
那会变成一个业务决定(那些坏引用怎么处理)。

## 确认过的事

- `upgrade()` 段内**零个 drop / alter** —— 只有 6 张 create_table、
  12 个 create_index、2 个 create_foreign_key。
  (文件里有 20 个 `op.drop`,**全在 `downgrade()` 里**,是对称回滚。
   ⚠️ 一个粗暴的 `grep -c "op.drop"` 会让人以为这份迁移在删东西 ——
   **数一个数之前先确认数的是哪一段**。)
- 这一点是**刻意验的**:09-29 那版 autogenerate 要删掉幂等和
  「一个应用只有一份候选」两条真约束,前两版都扔了。
  > autogenerate 做的是「让库跟上模型」——
  > **模型漏声明的时候,它会安静地删掉一条真约束。**
  正确顺序是**先补契约声明,再生成迁移**,这次就是这么做的。

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ad8dfd07244'
down_revision: Union[str, Sequence[str], None] = '78e69d312111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_catalog_snapshots',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('catalog_hash', sa.Text(), nullable=True),
    sa.Column('tool_version_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokenizer_ref', sa.Text(), nullable=True),
    sa.Column('embedder_ref', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('build_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_tool_catalog_snapshots_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_tool_catalog_snapshots')
    )
    op.create_index('ix_tool_catalog_snapshots_proj_status', 'tool_catalog_snapshots', ['project_id', 'status'], unique=False)
    op.create_index('ix_tool_catalog_snapshots_proj_updated', 'tool_catalog_snapshots', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('tool_groups',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('draft_revision', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_tool_groups_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_tool_groups')
    )
    op.create_index('ix_tool_groups_proj_status', 'tool_groups', ['project_id', 'status'], unique=False)
    op.create_index('ix_tool_groups_proj_updated', 'tool_groups', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('tool_selection_policies',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('draft_revision', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_tool_selection_policies_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_tool_selection_policies')
    )
    op.create_index('ix_tool_selection_policies_proj_status', 'tool_selection_policies', ['project_id', 'status'], unique=False)
    op.create_index('ix_tool_selection_policies_proj_updated', 'tool_selection_policies', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('tool_group_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tool_group_id', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('member_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('companion_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_tool_group_versions_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'tool_group_id'], ['tool_groups.project_id', 'tool_groups.id'], name='fk_tool_group_versions_tool_groups', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_tool_group_versions')
    )
    op.create_index('ix_tool_group_versions_hash', 'tool_group_versions', ['content_hash'], unique=False)
    op.create_index('ix_tool_group_versions_proj_updated', 'tool_group_versions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('tool_selection_policy_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tool_selection_policy_id', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('selection_mode', sa.Text(), nullable=True),
    sa.Column('catalog_snapshot_ref', sa.Text(), nullable=True),
    sa.Column('default_group_version_ref', sa.Text(), nullable=True),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('loading_type', sa.Text(), nullable=True),
    sa.Column('empty_result_action', sa.Text(), nullable=True),
    sa.Column('catalog_error_action', sa.Text(), nullable=True),
    sa.Column('independent_router_enabled', sa.Boolean(), nullable=True),
    sa.Column('candidate_cache_enabled', sa.Boolean(), nullable=True),
    sa.Column('release_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_tool_selection_policy_versions_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'tool_selection_policy_id'], ['tool_selection_policies.project_id', 'tool_selection_policies.id'], name='fk_tool_selection_policy_versions_tool_selection_policies', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_tool_selection_policy_versions')
    )
    op.create_index('ix_tool_selection_policy_versions_hash', 'tool_selection_policy_versions', ['content_hash'], unique=False)
    op.create_index('ix_tool_selection_policy_versions_proj_updated', 'tool_selection_policy_versions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('selection_decisions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('execution_run_id', sa.Text(), nullable=True),
    sa.Column('run_step_id', sa.Text(), nullable=True),
    sa.Column('tool_selection_policy_version_id', sa.Text(), nullable=True),
    sa.Column('tool_catalog_snapshot_id', sa.Text(), nullable=True),
    sa.Column('capability_query', sa.Text(), nullable=True),
    sa.Column('normalized_query', sa.Text(), nullable=True),
    sa.Column('candidate_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('loaded_version_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('not_loaded_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('authz_fingerprint_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('rediscovery_no', sa.Integer(), nullable=True),
    sa.Column('parent_decision_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_selection_decisions_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'execution_run_id'], ['execution_runs.project_id', 'execution_runs.id'], name='fk_selection_decisions_execution_runs', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'run_step_id'], ['run_steps.project_id', 'run_steps.id'], name='fk_selection_decisions_run_steps', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'tool_catalog_snapshot_id'], ['tool_catalog_snapshots.project_id', 'tool_catalog_snapshots.id'], name='fk_selection_decisions_tool_catalog_snapshots', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'tool_selection_policy_version_id'], ['tool_selection_policy_versions.project_id', 'tool_selection_policy_versions.id'], name='fk_selection_decisions_tool_selection_policy_versions', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_selection_decisions')
    )
    op.create_index('ix_selection_decisions_proj_status', 'selection_decisions', ['project_id', 'status'], unique=False)
    op.create_index('ix_selection_decisions_proj_updated', 'selection_decisions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_foreign_key('fk_connection_versions_model_connections', 'connection_versions', 'model_connections', ['project_id', 'connection_id'], ['project_id', 'id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_tool_versions_capability_connections', 'tool_versions', 'capability_connections', ['project_id', 'connection_id'], ['project_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tool_versions_capability_connections', 'tool_versions', type_='foreignkey')
    op.drop_constraint('fk_connection_versions_model_connections', 'connection_versions', type_='foreignkey')
    op.drop_index('ix_selection_decisions_proj_updated', table_name='selection_decisions')
    op.drop_index('ix_selection_decisions_proj_status', table_name='selection_decisions')
    op.drop_table('selection_decisions')
    op.drop_index('ix_tool_selection_policy_versions_proj_updated', table_name='tool_selection_policy_versions')
    op.drop_index('ix_tool_selection_policy_versions_hash', table_name='tool_selection_policy_versions')
    op.drop_table('tool_selection_policy_versions')
    op.drop_index('ix_tool_group_versions_proj_updated', table_name='tool_group_versions')
    op.drop_index('ix_tool_group_versions_hash', table_name='tool_group_versions')
    op.drop_table('tool_group_versions')
    op.drop_index('ix_tool_selection_policies_proj_updated', table_name='tool_selection_policies')
    op.drop_index('ix_tool_selection_policies_proj_status', table_name='tool_selection_policies')
    op.drop_table('tool_selection_policies')
    op.drop_index('ix_tool_groups_proj_updated', table_name='tool_groups')
    op.drop_index('ix_tool_groups_proj_status', table_name='tool_groups')
    op.drop_table('tool_groups')
    op.drop_index('ix_tool_catalog_snapshots_proj_updated', table_name='tool_catalog_snapshots')
    op.drop_index('ix_tool_catalog_snapshots_proj_status', table_name='tool_catalog_snapshots')
    op.drop_table('tool_catalog_snapshots')
    # ### end Alembic commands ###
