"""Agent 版本加「加载方式」和策略版本引用:**为空读成全部加载**

## 这一条是规格 §16 第一阶段那句兼容性要求的唯一落点

规格 §16 第一阶段的验收写的是:
「**旧 Agent 默认继续原加载方式**,配置迁移有回退」。

两列都 **nullable=True**,而且这不是图方便:

- `agent_versions` 是**不可变**的版本表 —— 已有的版本这一列**永远是 NULL**,
  不可能回去补。
- 所以实现必须把 **NULL 读成「全部加载」**,不是「未配置」。
  当成「未配置」然后报错的话,**所有历史 Agent 版本会在升级那一刻一起失效**
  —— 而建表、迁移、`alembic check` 全是绿的。

规格 §13.2 原话也说「全部加载……**保留作为旧配置兼容及对比基线**」:
它不是过渡态,是个永久选项 —— **没有基线就没法说筛选是不是更好。**

## 另一条写进 entities 约束的事

规格 §13.2:「策略包含不在 Agent 允许范围内的必要工具时**阻止冻结**并定位冲突,
**不能自动勾选授权**」。

自动勾上就等于让筛选策略成了一条发权限的路 ——
而规格 §3 明写「**筛选得分高不授予权限**」。

## 确认过

`upgrade()` 只有 2 个 add_column(都可空)+ 1 个 create_foreign_key,
**零个 drop / alter**。外键带 ondelete=RESTRICT 和 project_id(项目隔离)。

⚠️ 那个外键列名是**全称** `tool_selection_policy_version_id`:
短名推不出外键,而推不出来的表现是**静默不建** ——
同一天在 `selection_decisions` 上踩过一次,见 `tools/fk_dep_check.py`。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b113f98fb970'
down_revision: Union[str, Sequence[str], None] = '9ad8dfd07244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_versions', sa.Column('tool_loading_type', sa.Text(), nullable=True))
    op.add_column('agent_versions', sa.Column('tool_selection_policy_version_id', sa.Text(), nullable=True))
    op.create_foreign_key('fk_agent_versions_tool_selection_policy_versions', 'agent_versions', 'tool_selection_policy_versions', ['project_id', 'tool_selection_policy_version_id'], ['project_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_agent_versions_tool_selection_policy_versions', 'agent_versions', type_='foreignkey')
    op.drop_column('agent_versions', 'tool_selection_policy_version_id')
    op.drop_column('agent_versions', 'tool_loading_type')
    # ### end Alembic commands ###
