"""execution_runs 加两列:受理时冻结的执行策略 + Run 开始时采用的(两个都存,不一致就停)

Revision ID: d2ba00576e59
Revises: fd52eb646a81
Create Date: 2026-10-06 12:58:37.035153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2ba00576e59'
down_revision: Union[str, Sequence[str], None] = 'fd52eb646a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_runs', sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('execution_runs', sa.Column('adopted_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_runs', 'adopted_policy_snapshot')
    op.drop_column('execution_runs', 'policy_snapshot')
    # ### end Alembic commands ###
