"""筛选策略加「路由实验」和「路由模型连接」—— 开独立路由的条件落成列

## 为什么要这两列

规格 §4.2 给的是**条件**,不是一个开关:

> 筛选语句可由执行任务的 Agent 直接产生,不强制单独调用「路由大模型」。
> **只有实验证明额外分类有价值时,才启用独立路由节点**;
> 它的成本和延迟计入整条任务。

而在这之前 `independent_router_enabled` **一道闸都没有** —— 只是 `bool()` 收下来。

> **一个没有实验撑着的「已启用」,和一个有实验撑着的,在策略页上长得一模一样。**

- `router_evidence_ref` → 指一次**已完成**的评测(规格那句「实验」的落点)
- `router_connection_id` → 规格 §9.6 要的「模型连接」
  (原话:「模型路由 | 默认关闭的选项 | 开启后选**模型连接、Prompt 版本与预算**」)

## ⚠️ `router_connection_id` 指的是 `model_connections`,不是 `capability_connections`

第一版这个外键建到了 `capability_connections`(**工具**连接)上 —— **接错了表**。
后台有两张连接表,而规格要的是「模型连接」:

    capability_connections   工具连接(没有探测口)
    model_connections        模型连接(有 `POST /model-connections/{id}/probe`)

是撞见那个探测口才发现的。**外键建错了表,在列表上完全看不出来** ——
所以这一版在推之前先 downgrade、改契约、重新生成,
**没有留下「先建错再修」那两条迁移**。

## 两个都是复合外键(带 project_id)

不带项目范围的话,一个项目的策略能指到另一个项目的评测,**而那在列表上看不出来**。

⚠️ 这两列的名字里都没有被依赖表的名字(`router_evidence_ref` 不叫
`evaluation_id`),按表名推列名**推不出来** —— 而推不出来是**静默 continue**。
所以进了 `models.py::_依赖列` 的显式映射。
> 「我声明了依赖所以有外键」和「我声明了依赖但列名推不出来所以没外键」,
> **在登记表上长得一模一样** —— 这个仓库为这一条栽过两次。

## 旧行怎么办

两列**可空**。已有的策略版本里 `independent_router_enabled` 都是 false,
所以它们不需要证据 —— **空 = 那一版没开路由**,不是「开了但没记证据」。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41b8170e086'
down_revision: Union[str, Sequence[str], None] = '14979be496d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_selection_policy_versions', sa.Column('router_evidence_ref', sa.Text(), nullable=True))
    op.add_column('tool_selection_policy_versions', sa.Column('router_connection_id', sa.Text(), nullable=True))
    op.create_foreign_key('fk_tool_selection_policy_versions_model_connections', 'tool_selection_policy_versions', 'model_connections', ['project_id', 'router_connection_id'], ['project_id', 'id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_tool_selection_policy_versions_evaluations', 'tool_selection_policy_versions', 'evaluations', ['project_id', 'router_evidence_ref'], ['project_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tool_selection_policy_versions_evaluations', 'tool_selection_policy_versions', type_='foreignkey')
    op.drop_constraint('fk_tool_selection_policy_versions_model_connections', 'tool_selection_policy_versions', type_='foreignkey')
    op.drop_column('tool_selection_policy_versions', 'router_connection_id')
    op.drop_column('tool_selection_policy_versions', 'router_evidence_ref')
    # ### end Alembic commands ###
