"""产出监督:artifacts(应用层产出)+ artifact_decisions(打回决定)

用户 2026-10-10:报告和 agent 建议「是怎么生成的」要能在 AI 管理平台上**看 + 打回**。

## 为什么是两张新表,而不是挂在 traces / feedback 上

- 产出(一份周报、一条给导购的建议)**不是一次调用**:报告是店长在一轮对话里让模型写、
  再自己存下的;建议是上新那一刻由程序调一次模型写的。一份产出对应**零到一条**调用链,
  挂在 traces 上会让「没有调用链的产出」(规则模板退回的那种)无处可放。
- 打回**不是一次判读**(feedback 是「人认不认这次调用的结论」):它要**被执行**
  —— 澜绣拉回去重写建议 / 给报告标打回 —— 所以要有「待执行 → 已执行 / 执行失败」这条状态。

## 方向(和 A3 同一条判据推出来的)

管理后台**绝不反查澜绣的库**,也**不反写**:产出由澜绣推过来,打回决定由澜绣拉回去执行。

## 三道库层约束,每一道对着一种「看起来正常」的坏

- `uq_artifacts_project_id_external_ref_version_no`:同一份产出的同一版只记一行。
  重复上报变成两行的话,打回挂在其中一条上,另一条在列表里显示「正常」。
- `uq_artifact_decisions_one_pending`(部分唯一):同一份产出同时只能有一条待执行的打回。
  两个人同时点打回时,接口里的 if 两边都看到「还没有」——两条待执行会让澜绣重写两次。
- `ck_*`:类型 / 状态 / 结果只收登记过的几个值 —— 拼错的值会自成一档,筛选时哪档都不算。

Revision ID: f432d534324a
Revises: 35fcfbfaf961
Create Date: 2026-10-10 10:33:07.972899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f432d534324a'
down_revision: Union[str, Sequence[str], None] = '35fcfbfaf961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('external_ref', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('shop_name', sa.Text(), nullable=True),
    sa.Column('world_date', sa.Date(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('generation_type', sa.Text(), nullable=True),
    sa.Column('rule_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('external_trace_ref', sa.Text(), nullable=True),
    sa.Column('report_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("generation_type is null or generation_type in ('模型', '规则', '对话')", name='ck_artifacts_generation_type'),
    sa.CheckConstraint("kind in ('报告', '建议')", name='ck_artifacts_kind'),
    sa.CheckConstraint('version_no >= 1', name='ck_artifacts_version_no'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_artifacts_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_artifacts'),
    sa.UniqueConstraint('project_id', 'external_ref', 'version_no', name='uq_artifacts_project_id_external_ref_version_no')
    )
    op.create_index('ix_artifacts_proj_updated', 'artifacts', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('artifact_decisions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('artifact_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('result_note', sa.Text(), nullable=True),
    sa.Column('new_version_no', sa.Integer(), nullable=True),
    sa.Column('acked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("action in ('打回')", name='ck_artifact_decisions_action'),
    sa.CheckConstraint("result is null or result in ('已重写', '已标记', '执行失败')", name='ck_artifact_decisions_result'),
    sa.CheckConstraint("status in ('待执行', '已执行', '执行失败')", name='ck_artifact_decisions_status'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_artifact_decisions_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'artifact_id'], ['artifacts.project_id', 'artifacts.id'], name='fk_artifact_decisions_artifacts', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_artifact_decisions')
    )
    op.create_index('ix_artifact_decisions_proj_status', 'artifact_decisions', ['project_id', 'status'], unique=False)
    op.create_index('ix_artifact_decisions_proj_updated', 'artifact_decisions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('uq_artifact_decisions_one_pending', 'artifact_decisions', ['project_id', 'artifact_id'], unique=True, postgresql_where=sa.text("status = '待执行'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_artifact_decisions_one_pending', table_name='artifact_decisions', postgresql_where=sa.text("status = '待执行'"))
    op.drop_index('ix_artifact_decisions_proj_updated', table_name='artifact_decisions')
    op.drop_index('ix_artifact_decisions_proj_status', table_name='artifact_decisions')
    op.drop_table('artifact_decisions')
    op.drop_index('ix_artifacts_proj_updated', table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
