"""能力快照补内容哈希:它要能回答「这次探测和上次比能力变了吗」

Revision ID: fa742b8ca022
Revises: 8b4ab4df1497
Create Date: 2026-10-04 12:28:07.521982


## 这一条是**契约检查逼出来的**,而它逼对了

上一条迁移(8b4ab4df1497)把 `cache_capability_snapshots` 和 `cache_decisions`
都标成了「不可变」。`make contract` 当场红:
「内容寻址的实体都有哈希(认出「同一份内容」靠它,不靠名字和时间)」—— 点名这两张表。

判据分得比我准:**不可变和只追加不是一回事。**

    不可变 = **内容寻址的制品** —— 同样的内容就是同一个,所以要哈希
    只追加 = **事件日志**       —— 两条内容相同的记录是两次不同的事件

所以两张表走了两个方向:

**① `cache_capability_snapshots` 加 `content_hash`** —— 它确实该内容寻址,
因为它要回答一个真问题:**「这次探测和上次比,能力变了吗」**。
没有哈希的话,每次探测都得新建一行,而
**「能力真变了」和「只是又探了一次」在表上长得一模一样** ——
而规格 §8.2 要求的恰恰是「无证据显示『配置已保存,运行接入未验证』」。

**② `cache_decisions` 从「不可变」改成「只追加」**,于是按只追加的规矩
去掉 `revision` / `updated_at` / `archived_at` 三列。
给事件日志加内容哈希会让「同一个请求被判了两次」合成一行,
**而那正是要查的东西**(规格 §15.1:只追加;附录 A-8 的夹具里有「重复事件」)。

⚠️ 只追加表**不给 UPDATE 留位置**是这个仓库的既有约定(`models.py` 文件头):
「字段都不存在,改它就得先改表(而改表会被看见)」。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa742b8ca022'
down_revision: Union[str, Sequence[str], None] = '8b4ab4df1497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cache_capability_snapshots', sa.Column('content_hash', sa.Text(), nullable=True))
    op.create_index('ix_cache_capability_snapshots_hash', 'cache_capability_snapshots', ['content_hash'], unique=False)
    op.drop_index(op.f('ix_cache_decisions_proj_updated'), table_name='cache_decisions')
    op.drop_column('cache_decisions', 'archived_at')
    op.drop_column('cache_decisions', 'revision')
    op.drop_column('cache_decisions', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cache_decisions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('cache_decisions', sa.Column('revision', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('cache_decisions', sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_cache_decisions_proj_updated'), 'cache_decisions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.drop_index('ix_cache_capability_snapshots_hash', table_name='cache_capability_snapshots')
    op.drop_column('cache_capability_snapshots', 'content_hash')
    # ### end Alembic commands ###
