"""执行上限四个对象 + 清单与 Trace 的采用证据

规格「工具调用上限与防循环监控」§4.2 / §10.2。

## 为什么只新建四张表,**没有新建发布对象**

规格 §4.1:「**优先扩展现有版本/发布对象**并引用
`execution_policy_version_id`。如确需新增表,**仅新增版本、实例回执与
预算账本等缺少的对象**」。

发布那一侧**已经齐了**:`release_manifests`(不可变,带 content_hash /
approval)+ `environment_bindings`(环境指针,原子变更)。
所以「版本已发布」这个状态由现有对象承担,策略只要**进那张清单**。

⚠️ 而「进那张清单」有前车之鉴,就在契约文件里:`release_manifests`
2026-10-02 补过 `agent_version_id`,因为清单「记了 prompt / 连接 / 索引 /
检索配置 / 模型产物,**唯独没有 Agent 版本**」,后果是整个库答不出
「停用这个工具会不会影响线上」。
**执行策略不进清单的话,「改了调用上限会不会影响线上」原样再答不出一次。**

## 规格 §4.2 的四个状态,这一版之后各自落在哪

    ① 草稿已保存      现有草稿对象(有 revision)
    ② 版本已发布      execution_policy_versions + release_manifests
                      + environment_bindings
    ③ 实例已加载      policy_instance_receipts  ← **这一类原来整个是缺的**
    ④ 本次运行已采用   traces.policy_snapshot(**快照本身,不只是外键**)

## 三个判断值得写下来

**① 回执是只追加,不是不可变。**
规格 §10.2 明写「同一实例**定期更新**」—— 同一个实例反复回执同一个哈希,
是「它还在用这一版」被确认了很多次,不是一行。
(上次 `cache_decisions` 在这个判断上被契约检查顶过,这次先想清了:
不可变 = 内容寻址的制品;只追加 = 事件日志。)

**② `traces.policy_snapshot` 存快照本身。**
环境指针是**可改**的,而规格 §4.2 要求「同一任务启动后固定策略快照」
「不能借其他运行的回执证明本次生效」。只存外键的话,指针一变,
**历史运行会跟着改口**说自己当时用的是新版 ——
> 一个事后跟着指针漂的「当时用的策略」,和一个真记下来的,
> **在那一栏上长得一模一样。**

**③ 下面那一串约束是手工补的,因为 autogenerate 生成不出来。**
它从契约里读得出字段,读不出「`entry_kind` 只能是这两个值」
「一个任务只能有一本账」「理由不许是空串」——
> 一张**只有列而没有约束**的表,和一张真的拦得住的,
> **在那份 schema 文档上长得一模一样。**

## Trace 那六列为什么都可空

`traces` 是只追加的历史表 —— 历史行没有这些事实,而
**给历史行填一个默认值等于编造**:一行「当时用了策略 X」的旧 trace,
和一行真用了 X 的,长得一模一样。
**NULL 在这里是「没说过」,不是 0。**

Revision ID: fd52eb646a81
Revises: fa742b8ca022
Create Date: 2026-10-04 15:16:05.986086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd52eb646a81'
down_revision: Union[str, Sequence[str], None] = 'fa742b8ca022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_policy_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('application_id', sa.Text(), nullable=True),
    sa.Column('entry_kind', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('counter_schema_version', sa.Text(), nullable=True),
    sa.Column('support_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_execution_policy_versions_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_execution_policy_versions')
    )
    op.create_index('ix_execution_policy_versions_hash', 'execution_policy_versions', ['content_hash'], unique=False)
    op.create_index('ix_execution_policy_versions_proj_updated', 'execution_policy_versions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('policy_instance_receipts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('instance_ref', sa.Text(), nullable=True),
    sa.Column('execution_policy_version_id', sa.Text(), nullable=True),
    sa.Column('policy_hash', sa.Text(), nullable=True),
    sa.Column('runner_version', sa.Text(), nullable=True),
    sa.Column('sdk_version', sa.Text(), nullable=True),
    sa.Column('capability_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('loaded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_policy_instance_receipts_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'execution_policy_version_id'], ['execution_policy_versions.project_id', 'execution_policy_versions.id'], name='fk_policy_instance_receipts_execution_policy_versions', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_policy_instance_receipts')
    )
    op.create_table('task_budget_ledgers',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('task_ref', sa.Text(), nullable=True),
    sa.Column('execution_policy_version_id', sa.Text(), nullable=True),
    sa.Column('quota_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consumed_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reserved_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deadline_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_task_budget_ledgers_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'execution_policy_version_id'], ['execution_policy_versions.project_id', 'execution_policy_versions.id'], name='fk_task_budget_ledgers_execution_policy_versions', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_task_budget_ledgers')
    )
    op.create_index('ix_task_budget_ledgers_proj_updated', 'task_budget_ledgers', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('budget_topups',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('task_budget_ledger_id', sa.Text(), nullable=True),
    sa.Column('before_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delta_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topup_reason', sa.Text(), nullable=True),
    sa.Column('approver_id', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_budget_topups_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'task_budget_ledger_id'], ['task_budget_ledgers.project_id', 'task_budget_ledgers.id'], name='fk_budget_topups_task_budget_ledgers', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_budget_topups')
    )
    op.add_column('release_manifests', sa.Column('execution_policy_version_id', sa.Text(), nullable=True))
    op.add_column('traces', sa.Column('task_ref', sa.Text(), nullable=True))
    op.add_column('traces', sa.Column('entry_kind', sa.Text(), nullable=True))
    op.add_column('traces', sa.Column('execution_policy_version_id', sa.Text(), nullable=True))
    op.add_column('traces', sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('traces', sa.Column('previous_trace_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # ── 手工补的约束 —— **autogenerate 生成不出这一段** ─────────────────
    #
    # 一张只有列而没有约束的表,和一张真的拦得住的,
    # **在那份 schema 文档上长得一模一样。**

    # ⚠️ 入口只有这两种。**认不出的入口要当场拒绝**,
    # 而不是存进去等运行时发现 —— 那时候它已经被当成一条有效策略了。
    op.create_check_constraint(
        "ck_exec_policy_entry_kind", "execution_policy_versions",
        "entry_kind in ('store_v3','admin_agent_loop')")
    # ⚠️ 计数口径也白名单(规则 §5.2)。一个拼错的口径名会让读数那一侧
    # 静默走到默认分支上 —— 而「用新口径读旧数」和「口径对上」
    # 在那个数字上长得一模一样。
    op.create_check_constraint(
        "ck_exec_policy_counter_schema", "execution_policy_versions",
        "counter_schema_version in ('legacy','v2')")
    op.create_check_constraint(
        "ck_exec_policy_ver_positive", "execution_policy_versions",
        "version_no > 0")
    # 同一应用同一入口下版本号不重复。
    op.create_unique_constraint(
        "uq_exec_policy_ver_no", "execution_policy_versions",
        ["project_id", "application_id", "entry_kind", "version_no"])

    # ⚠️ **一个任务一本账,所有 Run 段共享**(规格 §5.1)。
    # 不唯一的话,「重启后又开了一本」和「本来就是两个任务」长得一样 ——
    # 而前者正是 §6.3 点名禁止的「恢复时重新初始化成零」。
    op.create_unique_constraint(
        "uq_ledger_task", "task_budget_ledgers", ["project_id", "task_ref"])

    # 同一个追加请求发两次,**额度不许累计两份**(规格 C45)。
    op.create_unique_constraint(
        "uq_topup_idempotency", "budget_topups",
        ["project_id", "idempotency_key"])
    # ⚠️ 理由不许是空串 —— 一条没有理由的追加,和一条有理由的,
    # 在那张审计表上长得一样。而这张表存在的全部理由就是审计。
    op.create_check_constraint(
        "ck_topup_reason_nonempty", "budget_topups",
        "length(btrim(topup_reason)) > 0")

    # 查「这一版有几个实例回执了」和「这个实例最近报的是哪一版」都要快。
    op.create_index("ix_receipt_by_instance", "policy_instance_receipts",
                    ["project_id", "instance_ref", "loaded_at"])
    op.create_index("ix_traces_task", "traces", ["project_id", "task_ref"])


def downgrade() -> None:
    """Downgrade schema."""
    # 手工加的那两个索引:建在 traces / 回执上。
    # `traces` **不会被 drop**(它是既有表),所以它那个索引要显式删 ——
    # 回执表上那个随 drop_table 一起走。
    op.drop_index("ix_traces_task", table_name="traces")
    op.drop_index("ix_receipt_by_instance",
                  table_name="policy_instance_receipts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traces', 'previous_trace_id')
    op.drop_column('traces', 'policy_snapshot')
    op.drop_column('traces', 'execution_policy_version_id')
    op.drop_column('traces', 'entry_kind')
    op.drop_column('traces', 'task_ref')
    op.drop_column('release_manifests', 'execution_policy_version_id')
    op.drop_table('budget_topups')
    op.drop_index('ix_task_budget_ledgers_proj_updated', table_name='task_budget_ledgers')
    op.drop_table('task_budget_ledgers')
    op.drop_table('policy_instance_receipts')
    op.drop_index('ix_execution_policy_versions_proj_updated', table_name='execution_policy_versions')
    op.drop_index('ix_execution_policy_versions_hash', table_name='execution_policy_versions')
    op.drop_table('execution_policy_versions')
    # ### end Alembic commands ###
