"""prompt_versions 补上 (project_id,key,version_no) 唯一约束:同一个 key 两个 v1 原来是合法的

Revision ID: bb336f6af9a9
Revises: d27ac1db12d5
Create Date: 2026-09-26 14:59:06.734888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb336f6af9a9'
down_revision: Union[str, Sequence[str], None] = 'd27ac1db12d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_prompt_versions_project_id_key_version_no', 'prompt_versions', ['project_id', 'key', 'version_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_prompt_versions_project_id_key_version_no', 'prompt_versions', type_='unique')
    # ### end Alembic commands ###
