"""编排契约:Workflow/Agent/工具/运行/人工介入 17 张表,顺带给项目内唯一约束补上 project_id

Revision ID: d27ac1db12d5
Revises: 55de922d112c
Create Date: 2026-09-26 14:17:42.966329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd27ac1db12d5'
down_revision: Union[str, Sequence[str], None] = '55de922d112c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('draft_revision', sa.BigInteger(), nullable=True),
    sa.Column('validation_status', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_agents_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_agents')
    )
    op.create_index('ix_agents_proj_status', 'agents', ['project_id', 'status'], unique=False)
    op.create_index('ix_agents_proj_updated', 'agents', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('capability_connections',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('adapter', sa.Text(), nullable=True),
    sa.Column('allowed_endpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('secret_ref', sa.Text(), nullable=True),
    sa.Column('capability_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('last_health_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('health_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_capability_connections_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_capability_connections')
    )
    op.create_index('ix_capability_connections_proj_status', 'capability_connections', ['project_id', 'status'], unique=False)
    op.create_index('ix_capability_connections_proj_updated', 'capability_connections', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('rule_template', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trigger_point', sa.Text(), nullable=True),
    sa.Column('failure_strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('test_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_policy_versions_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_policy_versions'),
    sa.UniqueConstraint('project_id', 'name', 'version_no', name='uq_policy_versions_project_id_name_version_no')
    )
    op.create_index('ix_policy_versions_hash', 'policy_versions', ['content_hash'], unique=False)
    op.create_index('ix_policy_versions_proj_updated', 'policy_versions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('skill_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('applicable_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_status', sa.Text(), nullable=True),
    sa.Column('load_mode', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_skill_versions_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_skill_versions'),
    sa.UniqueConstraint('project_id', 'name', 'version_no', name='uq_skill_versions_project_id_name_version_no')
    )
    op.create_index('ix_skill_versions_hash', 'skill_versions', ['content_hash'], unique=False)
    op.create_index('ix_skill_versions_proj_updated', 'skill_versions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('tool_definitions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('side_effect_type', sa.Text(), nullable=True),
    sa.Column('adapter', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('draft_revision', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_tool_definitions_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_tool_definitions')
    )
    op.create_index('ix_tool_definitions_proj_status', 'tool_definitions', ['project_id', 'status'], unique=False)
    op.create_index('ix_tool_definitions_proj_updated', 'tool_definitions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('draft_revision', sa.BigInteger(), nullable=True),
    sa.Column('validation_status', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_workflows_projects', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_workflows')
    )
    op.create_index('ix_workflows_proj_status', 'workflows', ['project_id', 'status'], unique=False)
    op.create_index('ix_workflows_proj_updated', 'workflows', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('agent_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('agent_id', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('prompt_version_id', sa.Text(), nullable=True),
    sa.Column('connection_version_id', sa.Text(), nullable=True),
    sa.Column('task_template', sa.Text(), nullable=True),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completion_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('incomplete_strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_agent_versions_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'agent_id'], ['agents.project_id', 'agents.id'], name='fk_agent_versions_agents', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'connection_version_id'], ['connection_versions.project_id', 'connection_versions.id'], name='fk_agent_versions_connection_versions', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'prompt_version_id'], ['prompt_versions.project_id', 'prompt_versions.id'], name='fk_agent_versions_prompt_versions', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_agent_versions'),
    sa.UniqueConstraint('project_id', 'agent_id', 'version_no', name='uq_agent_versions_project_id_agent_id_version_no')
    )
    op.create_index('ix_agent_versions_hash', 'agent_versions', ['content_hash'], unique=False)
    op.create_index('ix_agent_versions_proj_updated', 'agent_versions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('graph_drafts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('workflow_id', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.Text(), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_graph_drafts_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'agent_id'], ['agents.project_id', 'agents.id'], name='fk_graph_drafts_agents', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'workflow_id'], ['workflows.project_id', 'workflows.id'], name='fk_graph_drafts_workflows', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_graph_drafts'),
    sa.UniqueConstraint('project_id', 'agent_id', name='uq_graph_drafts_project_id_agent_id'),
    sa.UniqueConstraint('project_id', 'workflow_id', name='uq_graph_drafts_project_id_workflow_id')
    )
    op.create_index('ix_graph_drafts_proj_updated', 'graph_drafts', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('tool_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tool_definition_id', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('model_description', sa.Text(), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('side_effect_type', sa.Text(), nullable=True),
    sa.Column('allowed_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmation_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('external_status_lookup', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('retry_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('redaction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('secret_ref', sa.Text(), nullable=True),
    sa.Column('connection_id', sa.Text(), nullable=True),
    sa.Column('server_bound_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pollable', sa.Boolean(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_tool_versions_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'tool_definition_id'], ['tool_definitions.project_id', 'tool_definitions.id'], name='fk_tool_versions_tool_definitions', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_tool_versions'),
    sa.UniqueConstraint('project_id', 'tool_definition_id', 'version_no', name='uq_tool_versions_project_id_tool_definition_id_version_no')
    )
    op.create_index('ix_tool_versions_hash', 'tool_versions', ['content_hash'], unique=False)
    op.create_index('ix_tool_versions_proj_updated', 'tool_versions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('workflow_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('workflow_id', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('definition_schema_version', sa.Text(), nullable=True),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logical_hash', sa.Text(), nullable=True),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_workflow_versions_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'workflow_id'], ['workflows.project_id', 'workflows.id'], name='fk_workflow_versions_workflows', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_workflow_versions'),
    sa.UniqueConstraint('project_id', 'workflow_id', 'version_no', name='uq_workflow_versions_project_id_workflow_id_version_no')
    )
    op.create_index('ix_workflow_versions_proj_updated', 'workflow_versions', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('execution_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('definition_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('release_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('definition_hash', sa.Text(), nullable=True),
    sa.Column('principal', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_run_id', sa.Text(), nullable=True),
    sa.Column('environment', sa.Text(), nullable=True),
    sa.Column('execution_mode', sa.Text(), nullable=True),
    sa.Column('completion_reason', sa.Text(), nullable=True),
    sa.Column('quality_evaluation_status', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('current_step_id', sa.Text(), nullable=True),
    sa.Column('output_ref', sa.Text(), nullable=True),
    sa.Column('usage_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checkpoint_seq', sa.BigInteger(), nullable=True),
    sa.Column('pause_requested', sa.Boolean(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_execution_runs_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'trace_id'], ['traces.project_id', 'traces.id'], name='fk_execution_runs_traces', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_execution_runs'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_execution_runs_project_id_idempotency_key')
    )
    op.create_index('ix_execution_runs_proj_status', 'execution_runs', ['project_id', 'status'], unique=False)
    op.create_index('ix_execution_runs_proj_updated', 'execution_runs', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('human_requests',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('execution_run_id', sa.Text(), nullable=True),
    sa.Column('run_step_id', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('payload_ref', sa.Text(), nullable=True),
    sa.Column('allowed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidate_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('arguments_hash', sa.Text(), nullable=True),
    sa.Column('tool_version_id', sa.Text(), nullable=True),
    sa.Column('target_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_human_requests_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'execution_run_id'], ['execution_runs.project_id', 'execution_runs.id'], name='fk_human_requests_execution_runs', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'tool_version_id'], ['tool_versions.project_id', 'tool_versions.id'], name='fk_human_requests_tool_versions', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_human_requests')
    )
    op.create_index('ix_human_requests_proj_status', 'human_requests', ['project_id', 'status'], unique=False)
    op.create_index('ix_human_requests_proj_updated', 'human_requests', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('run_checkpoints',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('execution_run_id', sa.Text(), nullable=True),
    sa.Column('seq', sa.BigInteger(), nullable=True),
    sa.Column('state_ref', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('engine_version', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_run_checkpoints_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'execution_run_id'], ['execution_runs.project_id', 'execution_runs.id'], name='fk_run_checkpoints_execution_runs', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_run_checkpoints'),
    sa.UniqueConstraint('project_id', 'execution_run_id', 'seq', name='uq_run_checkpoints_project_id_execution_run_id_seq')
    )
    op.create_index('ix_run_checkpoints_hash', 'run_checkpoints', ['content_hash'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('execution_run_id', sa.Text(), nullable=True),
    sa.Column('seq', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('step_id', sa.Text(), nullable=True),
    sa.Column('payload_ref', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_run_events_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'execution_run_id'], ['execution_runs.project_id', 'execution_runs.id'], name='fk_run_events_execution_runs', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_run_events'),
    sa.UniqueConstraint('project_id', 'execution_run_id', 'seq', name='uq_run_events_project_id_execution_run_id_seq')
    )
    op.create_table('run_steps',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('execution_run_id', sa.Text(), nullable=True),
    sa.Column('node_id', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('iteration_path', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('execution_key', sa.Text(), nullable=True),
    sa.Column('logical_action_id', sa.Text(), nullable=True),
    sa.Column('input_ref', sa.Text(), nullable=True),
    sa.Column('output_ref', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('branch_key', sa.Text(), nullable=True),
    sa.Column('skipped_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('span_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_run_steps_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'execution_run_id'], ['execution_runs.project_id', 'execution_runs.id'], name='fk_run_steps_execution_runs', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_run_steps'),
    sa.UniqueConstraint('project_id', 'execution_key', name='uq_run_steps_project_id_execution_key')
    )
    op.create_index('ix_run_steps_proj_status', 'run_steps', ['project_id', 'status'], unique=False)
    op.create_index('ix_run_steps_proj_updated', 'run_steps', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('human_decisions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('human_request_id', sa.Text(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('edited_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_revision', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_human_decisions_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'human_request_id'], ['human_requests.project_id', 'human_requests.id'], name='fk_human_decisions_human_requests', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_human_decisions'),
    sa.UniqueConstraint('project_id', 'human_request_id', 'request_revision', name='uq_human_decisions_project_id_human_request_id_request_revision')
    )
    op.create_table('tool_invocations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('run_step_id', sa.Text(), nullable=True),
    sa.Column('tool_version_id', sa.Text(), nullable=True),
    sa.Column('side_effect_type', sa.Text(), nullable=True),
    sa.Column('arguments_hash', sa.Text(), nullable=True),
    sa.Column('approval_ref', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('logical_action_id', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('execution_mode', sa.Text(), nullable=True),
    sa.Column('result_ref', sa.Text(), nullable=True),
    sa.Column('intent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('responded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('needs_human_check', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_tool_invocations_projects', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'run_step_id'], ['run_steps.project_id', 'run_steps.id'], name='fk_tool_invocations_run_steps', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'tool_version_id'], ['tool_versions.project_id', 'tool_versions.id'], name='fk_tool_invocations_tool_versions', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'id', name='pk_tool_invocations'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_tool_invocations_project_id_idempotency_key'),
    sa.UniqueConstraint('project_id', 'logical_action_id', name='uq_tool_invocations_project_id_logical_action_id')
    )
    op.create_index('ix_tool_invocations_proj_status', 'tool_invocations', ['project_id', 'status'], unique=False)
    op.create_index('ix_tool_invocations_proj_updated', 'tool_invocations', ['project_id', sa.literal_column('updated_at DESC')], unique=False)
    op.drop_constraint(op.f('uq_dataset_versions_dataset_id_content_hash'), 'dataset_versions', type_='unique')
    op.create_unique_constraint('uq_dataset_versions_project_id_dataset_id_content_hash', 'dataset_versions', ['project_id', 'dataset_id', 'content_hash'])
    op.drop_constraint(op.f('uq_document_versions_document_id_content_hash'), 'document_versions', type_='unique')
    op.create_unique_constraint('uq_document_versions_project_id_document_id_content_hash', 'document_versions', ['project_id', 'document_id', 'content_hash'])
    op.drop_constraint(op.f('uq_job_events_job_id_seq'), 'job_events', type_='unique')
    op.create_unique_constraint('uq_job_events_project_id_job_id_seq', 'job_events', ['project_id', 'job_id', 'seq'])
    op.drop_constraint(op.f('uq_jobs_idempotency_key'), 'jobs', type_='unique')
    op.create_unique_constraint('uq_jobs_project_id_idempotency_key', 'jobs', ['project_id', 'idempotency_key'])
    op.drop_constraint(op.f('uq_prompt_versions_key_content_hash'), 'prompt_versions', type_='unique')
    op.create_unique_constraint('uq_prompt_versions_project_id_key_content_hash', 'prompt_versions', ['project_id', 'key', 'content_hash'])
    op.drop_constraint(op.f('uq_release_manifests_application_id_content_hash'), 'release_manifests', type_='unique')
    op.create_unique_constraint('uq_release_manifests_project_id_application_id_content_hash', 'release_manifests', ['project_id', 'application_id', 'content_hash'])
    op.drop_constraint(op.f('uq_training_jobs_idempotency_key'), 'training_jobs', type_='unique')
    op.create_unique_constraint('uq_training_jobs_project_id_idempotency_key', 'training_jobs', ['project_id', 'idempotency_key'])
    op.drop_constraint(op.f('uq_usage_ledger_event_key'), 'usage_ledger', type_='unique')
    op.create_unique_constraint('uq_usage_ledger_project_id_event_key', 'usage_ledger', ['project_id', 'event_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usage_ledger_project_id_event_key', 'usage_ledger', type_='unique')
    op.create_unique_constraint(op.f('uq_usage_ledger_event_key'), 'usage_ledger', ['event_key'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_training_jobs_project_id_idempotency_key', 'training_jobs', type_='unique')
    op.create_unique_constraint(op.f('uq_training_jobs_idempotency_key'), 'training_jobs', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_release_manifests_project_id_application_id_content_hash', 'release_manifests', type_='unique')
    op.create_unique_constraint(op.f('uq_release_manifests_application_id_content_hash'), 'release_manifests', ['application_id', 'content_hash'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_prompt_versions_project_id_key_content_hash', 'prompt_versions', type_='unique')
    op.create_unique_constraint(op.f('uq_prompt_versions_key_content_hash'), 'prompt_versions', ['key', 'content_hash'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_jobs_project_id_idempotency_key', 'jobs', type_='unique')
    op.create_unique_constraint(op.f('uq_jobs_idempotency_key'), 'jobs', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_job_events_project_id_job_id_seq', 'job_events', type_='unique')
    op.create_unique_constraint(op.f('uq_job_events_job_id_seq'), 'job_events', ['job_id', 'seq'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_document_versions_project_id_document_id_content_hash', 'document_versions', type_='unique')
    op.create_unique_constraint(op.f('uq_document_versions_document_id_content_hash'), 'document_versions', ['document_id', 'content_hash'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_dataset_versions_project_id_dataset_id_content_hash', 'dataset_versions', type_='unique')
    op.create_unique_constraint(op.f('uq_dataset_versions_dataset_id_content_hash'), 'dataset_versions', ['dataset_id', 'content_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_tool_invocations_proj_updated', table_name='tool_invocations')
    op.drop_index('ix_tool_invocations_proj_status', table_name='tool_invocations')
    op.drop_table('tool_invocations')
    op.drop_table('human_decisions')
    op.drop_index('ix_run_steps_proj_updated', table_name='run_steps')
    op.drop_index('ix_run_steps_proj_status', table_name='run_steps')
    op.drop_table('run_steps')
    op.drop_table('run_events')
    op.drop_index('ix_run_checkpoints_hash', table_name='run_checkpoints')
    op.drop_table('run_checkpoints')
    op.drop_index('ix_human_requests_proj_updated', table_name='human_requests')
    op.drop_index('ix_human_requests_proj_status', table_name='human_requests')
    op.drop_table('human_requests')
    op.drop_index('ix_execution_runs_proj_updated', table_name='execution_runs')
    op.drop_index('ix_execution_runs_proj_status', table_name='execution_runs')
    op.drop_table('execution_runs')
    op.drop_index('ix_workflow_versions_proj_updated', table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index('ix_tool_versions_proj_updated', table_name='tool_versions')
    op.drop_index('ix_tool_versions_hash', table_name='tool_versions')
    op.drop_table('tool_versions')
    op.drop_index('ix_graph_drafts_proj_updated', table_name='graph_drafts')
    op.drop_table('graph_drafts')
    op.drop_index('ix_agent_versions_proj_updated', table_name='agent_versions')
    op.drop_index('ix_agent_versions_hash', table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_index('ix_workflows_proj_updated', table_name='workflows')
    op.drop_index('ix_workflows_proj_status', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('ix_tool_definitions_proj_updated', table_name='tool_definitions')
    op.drop_index('ix_tool_definitions_proj_status', table_name='tool_definitions')
    op.drop_table('tool_definitions')
    op.drop_index('ix_skill_versions_proj_updated', table_name='skill_versions')
    op.drop_index('ix_skill_versions_hash', table_name='skill_versions')
    op.drop_table('skill_versions')
    op.drop_index('ix_policy_versions_proj_updated', table_name='policy_versions')
    op.drop_index('ix_policy_versions_hash', table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index('ix_capability_connections_proj_updated', table_name='capability_connections')
    op.drop_index('ix_capability_connections_proj_status', table_name='capability_connections')
    op.drop_table('capability_connections')
    op.drop_index('ix_agents_proj_updated', table_name='agents')
    op.drop_index('ix_agents_proj_status', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
